 **Load the Dataset**

In [ ]:
# Import the Pandas library for data manipulation and analysis
import pandas as pd

In [ ]:
# Load the online retail dataset from a CSV file using Latin-1 encoding
# Use Latin-1 (ISO-8859-1) encoding to correctly read non-UTF-8 characters in the dataset
df = pd.read_csv("Data/online_retail_II.csv", encoding="latin-1")

In [ ]:
df.head()# Display the first 5 rows of the DataFrame

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [ ]:
# Get the number of rows and columns in the DataFrame
df.shape

(1067371, 8)

In [ ]:
# Display a summary of the DataFrame, including column names, data types, non-null counts, and memory usage
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  str
 1   StockCode    1067371 non-null  str
 2   Description  1062989 non-null  str
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  str
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 65.1 MB

**Clean the Data**

In [ ]:
'''Customer ID has missing values
1067371 - 824364 = 243,007 rows have no customer ID. 
We can't do customer analysis without knowing who bought so we'll drop these rows.'''
df = df.dropna(subset = ["Customer ID"])
print(df.shape)

(824364, 8)

In [8]:
# Keep only records with a positive quantity and display the updated DataFrame dimensions
df = df[df["Quantity"] > 0]
print(df.shape)

(805620, 8)

In [9]:
# Transform InvoiceDate from a string/object to a datetime data type for time-based analysis
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
print(df["InvoiceDate"].dtype)

datetime64[us]

In [10]:
# Create a Revenue column by multiplying Quantity and Price, then preview the first few rows of the DataFrame
df["Revenue"] = df["Quantity"] * df["Price"]
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [11]:
# Save the cleaned DataFrame to a CSV file without including the row index, then confirm the save operation
df.to_csv("Data/cleaned_retail.csv", index=False)
print("Saved!")

Saved!